version: '3'
services:
#  app:
#    container_name: app
#    image: 34234247632/otus-ha-hw:v1.0
#    networks:
#      - otus-ha-hw1
#    restart: always
#    entrypoint: /entrypoint.sh
#    ports:
#      - "8000:8000"
#    environment:
#      DB_HOST: db
#      DB_PASSWORD: example
  db:
    container_name: db
    image: postgres:14.4
    restart: always
    networks:
      - otus-ha-hw1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Europe/Moscow'

networks:
  otus-ha-hw1:
