version: '3'
services:
  app:
    container_name: app
    image: 34234247632/otus-ha-hw:v1.0
    networks:
      - otus-ha-hw1
    restart: always
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      DB_HOST:   mysql
      DB_PASSWORD: mysql
  mysql:
    image: mysql:8.0
    container_name: db
    restart: on-failure
    networks:
      - otus-ha-hw1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

networks:
  otus-ha-hw1:
